const messagesUz = {
  start: "Assalomu alaykum! Tilni tanlang.",
  welcome:"Botga xush kelibsiz! Murojaat yozish uchun ro'yxatdan o'ting.",
  changeLanguage: "Tilni o'zgartirish uchun tugmani bosing.",
  sendQuestion:"Murojaat yuborish",
  allQuestion:"Murojaatlarim",
  checkQuestion:"Murojaatni tekshirish",
  faq:"FAQ",
  service:"Hizmatlarimiz:",
  register:"Ro'yxatdan o'tish",
  username:"Iltimos, ismingizni kiriting:",
  surname:"Endi, familiyangizni kiriting:",
  phone:"Telefon raqam",
  phoneApprove:"Telefon raqamingizni quyidagi tugmani bosish orqali jo'nating!",
  error:"Xatolik yuz berdi, qayta urinib ko'ring.",
  saveUser:"Rahmat! Ma'lumotlaringiz qabul qilindi va saqlandi.",
  back:"Orqaga",
  selectQuestion:"Savolni tanlang:",
  faqError:"Kechirasiz, bu savolga javob topilmadi.",
  answer:"Javob:",
  writeQuestion:"Iltimos, murojaatingizni yozing:",
  registerError:"Siz ro'yxatdan o'tmagan ekansiz.",
  successQuestion:"Murojaatingiz muvaffaqiyatli yuborildi!",
  askId: "Iltimos, tekshirmoqchi bo'lgan murojaat ID raqamini kiriting:",
  notFound: "Bunday ID raqamli murojaat topilmadi yoki sizga tegishli emas.",
};

const messagesRu = {
  start: "Здравствуйте! Выберите язык.",
  welcome:"Добро пожаловать! Зарегистрируйтесь для написания заявки.",
  changeLanguage: "Нажмите кнопку для смены языка.",
  sendQuestion:"Отправить заявку",
  allQuestion:"Мои запросы",
  checkQuestion:"Проверить запрос",
  faq:"Часто задаваемые вопросы",
  service:"Наши услуги:",
  register:"Зарегистрироваться",
  username:"Пожалуйста, введите ваше имя:",
  surname:"Теперь введите вашу фамилию:",
  phone:"Номер телефона",
  phoneApprove:"Пожалуйста, отправьте свой номер телефона, нажав на кнопку ниже!",
  error:"Произошла ошибка, попробуйте снова.",
  saveUser:"Спасибо! Ваши данные были приняты и сохранены.",
  back:"Назад",
  selectQuestion:"Выберите вопрос:",
  faqError:"Извините, ответ на этот вопрос не найден.",
  answer:"Ответ:",
  writeQuestion:"Пожалуйста, напишите Ваш запрос:",
  registerError:"Вы не зарегистрированы.",
  successQuestion: "Ваш запрос успешно отправлен!",
  askId: "Пожалуйста, введите ID обращения, которое хотите проверить:",
  notFound: "Обращение с таким ID не найдено или оно не принадлежит вам.",
};

export { messagesUz, messagesRu };
